# Generated by Django 6.0.6 on 2026-06-22 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('company_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.companyproduct')),
            ],
            options={
                'ordering': ('company_product__product_master__name',),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('SALE_CANCEL', 'Sale Cancel'), ('PURCHASE_CANCEL', 'Purchase Cancel'), ('MANUAL_INCREASE', 'Manual Increase'), ('MANUAL_DECREASE', 'Manual Decrease')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('company_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.companyproduct')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
