# Generated by Django 6.0.6 on 2026-06-22 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250)),
                ('unit', models.CharField(choices=[('PIECE', 'Piece'), ('KG', 'Kg'), ('GRAM', 'Gram'), ('LITER', 'Liter'), ('ML', 'ML'), ('PACKET', 'Packet'), ('BOX', 'Box')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_products', to='companies.company')),
                ('product_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_products', to='products.productmaster')),
            ],
            options={
                'ordering': ('product_master__name',),
                'constraints': [models.UniqueConstraint(fields=('company', 'product_master'), name='unique_company_product_mapping')],
            },
        ),
    ]
